### ISSUE TITLE
Setting properties in build.gradle not working

### ISSUE THREAD

**Issue by jdwinfodesign** [eerohele/dita-ot-gradle#25] opened 2021-01-12 15:04 UTC
Setting properties does not work as expected. The output css directory is created, but the only CSS files that are placed there are commonltr.css and commonrtl.css. Nor is the link to the user CSS created in the HTML output. The temp dir is not created (or at least not in the intended place. Using this build.gradle.
`
plugins {
    id 'com.github.eerohele.dita-ot-gradle' version '0.7.0'
}

defaultTasks 'dita'

dita {
    ditaOt '../jdwinfodesign/DITA-OT-instances/dita-ot-3.5.4'
    // Point DITA-OT to the files you want to publish.
    input 'User_Guide-reuse-only.ditamap'
    // Tell DITA-OT what you want it to produce.
    transtype 'html5'
    // Choose DITAVAL.
    filter 'ditavals/product-sta.ditaval'
    // Choose output directory.
    output 'out/sta'

    properties {
        property(name: 'args.copycss', value: 'yes')
		property(name: 'args.cssroot', value: 'css')
		property(name: 'args.css', value: 'jdwinfodesign-html5.css')
		property(name: 'args.csspath', value: 'css')
		property(name: 'dita.temp.dir', value: 'temp')
		property(name: 'clean.temp', value: 'no')
    }	
}`

**Comment by infotexture** [comment] 2021-01-12 15:25
Looks like this isn't the Gradle plug-in's fault, but rather a limitation of the DITA-OT itself, which [requires an absolute path to the CSS root](https://www.dita-ot.org/dev/parameters/parameters-base-html.html#base-html__args.cssroot).

Try something like this to anchor the path to the project directory:

```groovy
property(name: 'args.cssroot', value: "${projectDir}/css/")
```

The missing CSS in output is usually a telltale sign of this error.

**Comment by eerohele** [comment] 2021-01-12 15:34
Using absolute paths is certainly a good practice, and probably a serviceable workaround. However, it is possible that this issue has the same root cause as https://github.com/eerohele/dita-ot-gradle/issues/24: on Java 8, Gradle resolves relative paths against the project root directory, while on newer versions, Gradle resolves them against `.gradle/daemon/$VERSION`.

I have no idea why this is, whether this is a feature or a bug, and whether it's an issue with Java or with Gradle, and where to even start looking, frankly.

I'll try to look into it, but I'm quite swamped at work at the moment, so I'm not sure how soon I'll get to it.

**Comment by eerohele** [comment] 2021-01-12 15:36
[This](https://github.com/gradle/gradle/issues/15380) sounds like the same issue.

**Comment by infotexture** [comment] 2021-01-12 15:47
@eerohele I bet you're right: this does sound like https://github.com/gradle/gradle/issues/15380.

That's certainly consistent with our experience in the [dita-ot/docs](https://github.com/dita-ot/docs) project, where values that worked with Java 8 stopped working with Java 11.

**Comment by jdwinfodesign** [comment] 2021-01-12 17:07
Neither of these work.
`property(name: 'args.cssroot', value: 'file:///c://Users/jdwin/Documents/jdwinfodesign/t-bird-demo/css')`
`property(name: 'args.cssroot', value: '${projectDir}/css')`

**Comment by eerohele** [comment] 2021-01-12 18:08
Not sure why the first option wouldn't work, but for the second, you need to use double quotes specifically for string interpolation to work.

That is, with `'${projectDir}/css'`, `projectDir` won't get expanded to the project root dir, but with `"${projectDir}/css"`, it will.

**Comment by eerohele** [comment] 2021-01-12 18:47
I looked into this a bit and I can't see any way to completely fix this issue in this plugin. I'm not sure Gradle can fix this, either, because as far as I can tell, JDK versions newer than 8 no longer let you override the `user.dir` system property, which is what Gradle did to set the current working directory to the project root directory.

I *can* fix this for `temp` because that's something this plugin can control, but I don't think I can do anything about paths you use `property` for.

It's a bit of hitch in the old giddy-up for sure. For now, I think your best bet is to use `"${projectDir}/foobar"` everywhere. Other than that, I'm not sure we can do much more than wait, at this point.

**Comment by jdwinfodesign** [comment] 2021-01-12 19:31
The double quotes worked. Thanks!

**Comment by eerohele** [comment] 2021-01-12 19:50
With 0.7.1, you should be able to use relative paths with `temp`.

With `property`, though, you'll need to use absolute paths, be it via `${projectDir}` or some other means, unfortunately.

**Comment by eerohele** [comment] 2021-01-12 19:59
I added [a section](https://github.com/eerohele/dita-ot-gradle#passing-ant-properties-to-dita-ot) on this topic in the README.

**Comment by eerohele** [comment] 2021-01-13 06:40
I'll close this issue. Please feel free to open a new issue if you come across anything else.

**Closed as completed by eerohele** 2021-01-13 06:40 UTC
