### ISSUE TITLE
Add DITA-OT plugin JAR files to classpath

### ISSUE THREAD

**Issue by jelovirt** [eerohele/dita-ot-gradle#12] opened 2017-10-15 09:05 UTC
Currently [`AntBuilderAssistant`](https://github.com/eerohele/dita-ot-gradle/blob/1560f31d7be1d45eb623a0e5e1e2411f5dbf9b61/src/main/groovy/com/github/eerohele/AntBuilderAssistant.groovy#L23) only adds PDF2 JARs to classpath:

```
'resources/',
'lib/**/*.jar',
'plugins/org.dita.pdf2/lib/fo.jar',
'plugins/org.dita.pdf2/build/libs/fo.jar'
```

Also, in DITA-OT 3.0 the configuration files have been moved from `resources` to `config` directory. 

The `getClasspath` should be modified to:

1. add `config` for DITA-OT 3.0
2. read `config/plugins.xml` (`resources/plugins.xml` in DITA-OT 2.x) and get list of plugin JARs from there. Then there will be no need to hard code PDF2 JARs

**Comment by eerohele** [comment] 2017-10-16 19:11
cc62d62e83f856543aea88c5ceae84ed841d4467 should fix the issue. I'll take a look at it with fresh eyes tomorrow and deploy a new version if it looks OK.

@jelovirt: If you have the time, could you give
https://github.com/eerohele/dita-ot-gradle/commit/cc62d62e83f856543aea88c5ceae84ed841d4467#diff-61637f024646c6410b55b1867e6a2b50R22 a quick once-over and see whether the logic looks OK to you?

**Comment by infotexture** [comment] 2017-10-18 15:49
👍 Tested 0.4.2 on dita-ot/docs@6c3e7fca with Gradle 3.5 and 4.2.1, seems to work fine.

Markdown topics are now treated as DITA, and built to HTML as expected, so the changes in cc62d62 are effective, and the new libraries from the external plug-ins are used.

**Comment by infotexture** [comment] 2017-10-18 16:33
Discovered a side-effect of the changes in cc62d62:

After updating the plug-in version in dita-ot/docs@6c3e7fca, when I ran `gradle wrapper` to upgrade to the latest Gradle version,

    FAILURE: Build failed with an exception.

> Can't find DITA-OT plugin XML file.
  Are you sure you're using a valid DITA-OT directory?

Not a show-stopper, as I can still upgrade the wrapper from a prior commit before the new plug-in version landed, but certainly unexpected.

**Comment by eerohele** [comment] 2017-10-18 17:14
Agh. Thanks for reporting the issue — I'll look into it.

**Comment by eerohele** [comment] 2017-10-18 17:17
I can't seem to reproduce the issue.

Which Gradle version do you have installed? As in, if you do `gradle --version`, what does it return?

Also, are you running `gradle wrapper` in the root directory of the DITA-OT docs repo?

**Comment by infotexture** [comment] 2017-10-19 09:16
```
~ D/W/D/docs > $ gradle --version

------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by infotexture** [comment] 2017-10-19 09:19
> Also, are you running gradle wrapper in the root directory of the DITA-OT docs repo?

Yes, however, my `docs` clone is alongside the `dita-ot` directory:

```
.
├── dita-ot
├── docs
```

**Comment by infotexture** [comment] 2017-10-19 09:20
If I explicitly pass gradle the `dita.home` location, it works:

    gradle wrapper -Ddita.home=../dita-ot/src/main

**Comment by eerohele** [comment] 2017-10-28 15:59
All right, so that exception was caused by a peculiarity in the previous version of the DITA-OT docs `build.gradle` file.

I think this issue is resolved. The remaining issue (that I know of) is that the plugin doesn't always include the `.gradle` directory in the up-to-date check even though it should. I'll create a new issue for that one.

**Closed as completed by eerohele** 2017-10-28 15:59 UTC
Labels: bug, enhancement
